### ISSUE TITLE
You don't need neither NET_RAW nor NET_BIN_SERVICE for normal app container

### ISSUE THREAD

**Issue by onorua** [konstruktoid/Docker#1]
NET_RAW is required to generate packets not supported by normal tcp/ip stack, such as ICMP, or traceroute or any application which need to change TCP header for work. You don't need it for ANY application aimed to be run inside docker container in production. 
NET_BIN_SERVICE gives possibility to listen to ports below 1024, as we all know that normal user can't do this, and it's really bad idea to run application in production under root user even in docker container.

**Comment by konstruktoid** [comment]
Hi @onorua, and thank you for your comment.  
I assume you're referring to ```--cap-add net_raw``` and ```~$ export CAP="--cap-drop all --cap-add net_bind_service --cap-add net_raw"``` in https://github.com/konstruktoid/Docker/blob/master/Security/CheatSheet.md.  
You're correct that those aren't capabilities you should enable in production environment, and I only used them as syntax examples, but you are most welcome do edit the document and file a PR with better CAP_ examples.
